name: CI/CD workflow for Laravel Build and Sonar Code Scan

on:
  push:
    branches:
      - main  # Cambia al nombre de tu rama principal si es diferente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código fuente
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Cambia a la versión de PHP que necesitas

      # 3. Configurar Java 17 (requerido por SonarQube)
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      # 4. Instalar dependencias de Composer para Laravel
      - name: Install Composer dependencies
        run: composer install --no-scripts --no-interaction

      # 5. Instalar SonarScanner
      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.0.2966-linux.zip
          unzip sonar-scanner-cli-5.0.0.2966-linux.zip
          mv sonar-scanner-5.0.0.2966-linux sonar-scanner
          echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH
        # Manejo de errores al instalar SonarScanner
        shell: bash
        continue-on-error: false

      # 6. Verificar que SonarScanner está instalado y en el PATH
      - name: Verify SonarScanner installation
        run: ./sonar-scanner/bin/sonar-scanner -v

      # 7. Ejecutar el análisis de SonarQube
      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./sonar-scanner/bin/sonar-scanner \
            -Dsonar.organization=my-org \
            -Dsonar.projectKey=my-laravel-app \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
        # Manejo de errores comunes en la ejecución de SonarScanner
        shell: bash
        continue-on-error: false
